SELECT * FROM people ORDER BY pid OFFSET 0 LIMIT 10;

SELECT * FROM people ORDER BY pid OFFSET 10 LIMIT 10;

SELECT * FROM people ORDER BY pid OFFSET 20 LIMIT 10;

SELECT * FROM people ORDER BY pid OFFSET 30 LIMIT 10;

SELECT * FROM people ORDER BY pid OFFSET 40 LIMIT 10;